name 'fabiomello-zabbix'
version '0.0.1'
author 'fabiomellobr'
license 'Apache License, Version 2.0'
project_page 'https://github.com/HEP-Puppet/motd'
source 'git@github.com:HEP-Puppet/motd.git'
summary 'A simple module to demonstrate managing /etc/motd as a template'
description 'This module simply manages /etc/motd as a template, showing interpolation of system attributes'
