name 'fabiomello-zabbix'
version '0.0.1'
author 'fabiomellobr'
license 'Apache License, Version 2.0'
project_page 'https://github.com/khony/puppet-zabbix'
source 'git@github.com:khony/puppet-zabbix.git'
summary 'A simple module to manage Zabbix'
description 'Module to manage Zabbix, include scripts'
